name = "StippleMathjs"
uuid = "7fb1dcd0-db8f-4201-9509-3dea5d7792e9"
authors = ["Helmut Hänsel <helmut.haensel@gmx.de>"]
version = "0.1.1"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"

[compat]
Genie = "5.23.2"
Stipple = "0.27.21"
julia = "1.6"

[extras]
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StippleUI"]
